cisco-open/cisco-catalyst-wan-sdk

catalystwan/endpoints/__init__.py, catalystwan/models/common.py, catalystwan/session.py, catalystwan/tests/test_endpoints.py, catalystwan/tests/test_models_common.py, pyproject.toml
It is now possible to have different serialization alias to be chosen dynamically based on running Manager api version.
This extends the possibility to reuse single payload model definition for different Manager API versions.
We are utilizing a new feature introduced in pydantic 2.7.0 [Ability to pass a context object to the serialization methods](https://github.com/pydantic/pydantic/issues/7143).
Context dict containing `api_version` key is provided before sending payload automatically when using methods decorated with `@post`, `@put` etc.
When model fields are annotated with `VersionedField` - model_serializer updates fields using helper when `api_version` is given in context.
- introduce `VersionedField` annotation
- introduce `update_model_fields()` helper
- automatically inject …
=> context based dynamic serialization

catalystwan/models/policy/centralized.py, catalystwan/models/policy/policy.py
It now possible to create CLI based centralized policy
```python
from catalystwan.models.policy import CentralizedPolicy 
from catalystwan.session import create_manager_session
with create_manager_session(...) as session:
cli_config_string = "<...>"
cli = CentralizedPolicy(policy_name="my-policy-cli", policy_type="cli", policy_definition=cli_config_string)
session.api.policy.centralized.create(cli)
```
=> allow centralized cli policy creation

catalystwan/models/configuration/feature_profile/sdwan/policy_object/__init__.py, catalystwan/models/configuration/feature_profile/sdwan/policy_object/policy/as_path.py, catalystwan/utils/config_migration/converters/policy/policy_lists.py
=> AS path model

catalystwan/api/policy_api.py, catalystwan/endpoints/configuration/policy/definition/url_filtering.py, catalystwan/models/policy/__init__.py, catalystwan/models/policy/definition/intrusion_prevention.py, catalystwan/models/policy/definition/url_filtering.py
Introducing URL filtering v1 model
=> Url filtering v1 model

catalystwan/models/policy/definition/intrusion_prevention.py
fix validation error
```
pydantic_core._pydantic_core.ValidationError: 1 validation error for IntrusionPreventionPolicyGetResponse
definition.signatureWhiteList.ref
Field required [type=missing, input_value={}, input_type=dict]
For further information visit https://errors.pydantic.dev/2.7/v/missing
```
=> Fix ValidationError for empty dict

catalystwan/abstractions.py, catalystwan/endpoints/__init__.py, catalystwan/response.py, catalystwan/session.py, catalystwan/tests/test_response.py
User can opt-out from response validation against pydantic model.
This might be useful when `ValidationError` disrupts program flow while malformed attribute is not important to user (eg. while testing new vmanage builds with possible api changes).
This setting is available as `ManagerSession().validate_responses` property. Default is `True` so change is  not breaking.
While flag is set to `False` we use `BaseModel.model_construct()` instead `BaseModel.model_validate()`. https://docs.pydantic.dev/latest/concepts/models/#creating-models-without-validation.
This affects all responses obtained by methods from:
`ManagerSession().request().dataobj(validate=...)`
`ManagerSession().request().dataseq(validate=...)`
`ManagerSession().endpoints`
```python
from catalystwan.session import …
```
=> allow disabling of response validation against pydantic model

catalystwan/exceptions.py, catalystwan/session.py
```python
from catalystwan.session import create_manager_session
with create_manager_session(...) as session:
session.api.users.delete("bogus-user-name")
session.put("/dataservice/settings/configuration/vedgecloud", {"certificateauthority": "enterprise"})
```
```
Traceback (most recent call last):
...
catalystwan.exceptions.ManagerHTTPError
```
```
Traceback (most recent call last):
...
catalystwan.exceptions.ManagerHTTPError: 500 Server Error: Internal Server Error for url: https://172.22.219.19:9912/dataservice/admin/user/bogus-user-name
message='Delete users request failed' details='Failed to process device request -  Error Message : bad-element:user' code='USER0006'
```
```
Traceback (most recent call last):
...
catalystwan.exceptions.ManagerHTTPError: 415 Client Error: Unsupported …
```
=> include original cause and info from server in ManagerHTTPError traceback

catalystwan/tests/test_typed_list.py, catalystwan/typed_list.py
Introduce `find()` method for DataSequence.
It works similarily like `filter()` but iteration stops when first object in sequence is detected. It guarantees that single object is returned (when no item found exception is raised)
```python
with create_manager_session(...) as session:
api = session.api.sdwan_feature_profiles.system
profile = api.get_profiles().filter(profile_name="system-1").single_or_default()
profile = api.get_profiles().find(profile_name="system-1")
```
=> introduce find method for DataSequence

catalystwan/session.py
Use `cached_property` for `api` and `endpoints` containers in `ManagerSession` class.
Import required modules on-demand.
_**This PR needs follow up: `APIContainer` and `APIEndpointContainer` classes properties also needs to utilize this trick so items are imported only when first used to further optimize load time.**_
Because `APIContainer` and `APIEndpointContainer` incorporate large number of pydantic models it could take long time before everything is imported for first time.
```python
from catalystwan.session import ManagerSession
session = ManagerSession(url="", username="", password="")
```
```
python -m cProfile test.py
```
```
6390615 function calls (5533081 primitive calls) in 2.241 seconds
```
```
408929 function calls (392369 primitive calls) in 0.246 seconds
```
=> fix session load time

ENDPOINTS.md, catalystwan/session.py, pyproject.toml
Tenant payload needs to be validated to access field aliases properly during login.
=> hotfix: tenant info fetch during provider-as-tenant login

catalystwan/api/alarms_api.py
In earlier release the rules=[] were shown in docstring, but they were not required.
Now starting in 20.15 they are required.
The default rules has not changed, should be fine backward compatible.
Added a default rules=[] for alarms.
`rules = [{"field": "active", "type": "boolean", "value": ["true"], "operator": "equal"}]`
=> alarms-20.15

catalystwan/tests/config_migration/test_utils.py, catalystwan/utils/config_migration/converters/feature_template/bgp.py, catalystwan/utils/config_migration/converters/feature_template/ethernet.py, catalystwan/utils/config_migration/converters/feature_template/lan/ethernet.py, catalystwan/utils/config_migration/converters/feature_template/wan/ethernet.py, catalystwan/utils/config_migration/converters/utils.py
Convert UX1.0 ethernet interface names to conform to UX2.0 regex
- eth -> Ethernet
- ge -> GigabitEthernet
Cover case where templates created by system have interface name that don't pass regex
=> dev-uxmt: Fix: Add interface name converter to ethernet

catalystwan/models/configuration/config_migration.py, catalystwan/utils/config_migration/converters/policy/policy_definitions.py, catalystwan/utils/config_migration/creators/config_pusher.py, catalystwan/utils/config_migration/creators/policy_object_pusher.py
- add `TopologyGroup` and `PolicyGroup` reporting
- add `PushContext` object which will contain various items updated during push process (currently it stores id lookup needed to find pushed item id by its origin id)
Note: Topology push is currently in draft, dedicated pusher will be created (it is used to fill report for quick UI integration with config-migration-tool)
=> dev-uxmt: add policy push reporting and context

catalystwan/endpoints/configuration_settings.py
Fields validityPeriod and retrieveInterval are not required in model configuration_settings.Certificate
=> Issues/698 Optional fields validityPeriod and retrieveInterval

catalystwan/api/config_group_api.py
Clear ux2 function raises an Exception during clearing the config groups with attached devices.
Before an attempt to delete the config group, count of attached devices shall be checked -> if any available then it must be disassociated firstly.
=> Clearing config groups fix

catalystwan/models/configuration/config_migration.py, catalystwan/tests/config_migration/policy_converters/test_acl_ipv4.py, catalystwan/tests/config_migration/policy_converters/test_acl_ipv6.py, catalystwan/tests/config_migration/policy_converters/test_aip_converter.py, catalystwan/tests/config_migration/policy_converters/test_amp_converter.py, catalystwan/tests/config_migration/policy_converters/test_device_access_ipv4.py, catalystwan/tests/config_migration/policy_converters/test_device_access_ipv6.py, catalystwan/tests/config_migration/policy_converters/test_dns_security_converter.py, catalystwan/tests/config_migration/policy_converters/test_extended_community_converter.py, catalystwan/tests/config_migration/policy_converters/test_intrusion_prevention.py, catalystwan/tests/config_migration/policy_converters/test_mirror_converter.py, catalystwan/tests/config_migration/policy_converters/test_route_converter.py, catalystwan/tests/config_migration/policy_converters/test_ssl_decryption_converter.py, catalystwan/tests/config_migration/policy_converters/test_ssl_profile_converter.py, catalystwan/tests/test_url_filtering_converter.py, catalystwan/utils/config_migration/converters/policy/policy_definitions.py, catalystwan/utils/config_migration/converters/policy/policy_lists.py, catalystwan/workflows/config_migration.py
Currently when converting an item result can by only pass (output item is provided) or fail (no output item is provided)
This PR introduces more options to better track and report unsupported or partially converted items.
This PR introduces:
```python
TO = TypeVar("TO")
ConvertOutputStatus = Literal["complete", "partial"]
ConvertAbortStatus = Literal["failed", "unsupported"]
ConvertStatus = Literal[ConvertOutputStatus, ConvertAbortStatus]
@dataclass
class ConvertResult(Generic[TO]):
status: ConvertStatus = "complete"
output: Optional[TO] = None
info: List[str] = field(default_factory=list)
```
`ConvertResult` is generic type that wraps conversion output with additional data which can be provided by converter.
Another change is `ConfigTransformResult` contains additional field …
=> dev-uxmt: additional convert result handling and reporting

catalystwan/api/feature_profile_api.py, catalystwan/api/templates/device_template/device_template.py, catalystwan/integration_tests/feature_profile/sdwan/test_extended_community.py, catalystwan/integration_tests/feature_profile/sdwan/test_ssl_decryption.py, catalystwan/models/configuration/config_migration.py, catalystwan/models/configuration/feature_profile/sdwan/acl/ipv6acl.py, catalystwan/models/configuration/feature_profile/sdwan/service/route_policy.py, catalystwan/models/configuration/feature_profile/sdwan/system/device_access.py, catalystwan/models/configuration/feature_profile/sdwan/system/device_access_ipv6.py, catalystwan/models/configuration/feature_profile/sdwan/transport/__init__.py, catalystwan/models/policy/policy.py, catalystwan/tests/config_migration/policy_converters/test_references_updater.py, catalystwan/utils/config_migration/creators/config_pusher.py, catalystwan/utils/config_migration/creators/groups_of_interests_pusher.py, catalystwan/utils/config_migration/creators/localized_policy_pusher.py, catalystwan/utils/config_migration/creators/references_updater.py, catalystwan/utils/config_migration/runner.py, catalystwan/workflows/config_migration.py, examples/parcel_configuration_guide.py
push converted localized policy elements to config group profile parcels
Implement pushing of following parcel types:
`ipv4-device-access-policy`
`ipv6-device-access-policy`
`ipv4-acl`
`ipv6-acl`
`route`
=> dev-uxmt: push converted localized policy elements to config group profile parcels

catalystwan/models/configuration/config_migration.py, catalystwan/utils/config_migration/runner.py, catalystwan/workflows/config_migration.py
remove adding suffix in transform() by default
ConfigMigrationRunner is still providing suffix by default when performing transform
=> dev-uxmt: no suffix in transform defaults

catalystwan/utils/config_migration/converters/feature_template/base.py, pyproject.toml
Guard FT converters against common exceptions when manipulating collections which are not fully typed
=> dev-uxmt: FT convert guard

catalystwan/session.py
When property `request_timeout` (default is None) is set on session - it will override value provided to `request` method.
=> add: session scoped request timeout

catalystwan/models/configuration/config_migration.py, catalystwan/tests/config_migration/policy_converters/test_aspath.py, catalystwan/utils/config_migration/converters/policy/policy_lists.py
- add as-path converter
- add unit tests
```
There is a mismatch between UX1 and UX2 models:
UX1:
- AS Path List Name (Alphanumeric value for vEdge, or number from 1 to 500 for ISR Edge router)
- AS Path list
UX2:
- Parcel name
- Parcel description
- AS Path List ID (Number from 1 to 500)
- AS Path list
The UX1 and UX2 intersection in AS Path list name and ID but only for the ISR Edge router (number 1 to 500).
If there is number we can insert the value in as_path_list_num field otherwise we will
generate the value and keep track of it in the context.
```
=> dev-uxmt: Converter: as-path

catalystwan/api/admin_tech_api.py, catalystwan/tests/test_admin_tech_api.py
Generate admintech request is not blocking in latest releases (>=20.15)
Thus filename is returned which is not completed yet.
Use same mechanism to check completeness as before delete operation - this will keep compatibility with previous versions.
=> Use polling to check if admintech generated

pyproject.toml
- possible fix to failing github actions jobs
=> Lock mypy lower than 1.11.0

catalystwan/api/administration.py, catalystwan/endpoints/configuration_settings.py, catalystwan/integration_tests/test_settings.py, catalystwan/models/settings.py, catalystwan/tests/config_migration/policy_converters/test_threat_grid_api.py
=> Fix threat

catalystwan/models/common.py, catalystwan/models/configuration/feature_profile/sdwan/embedded_security/ngfirewall.py, catalystwan/models/configuration/feature_profile/sdwan/policy_object/security/zone.py, catalystwan/models/configuration/feature_profile/sdwan/service/service_insertion_attachment.py, catalystwan/models/policy/list/zone.py, catalystwan/tests/config_migration/policy_converters/test_zone_based_firewall_converter.py, catalystwan/tests/config_migration/test_transform.py, catalystwan/utils/config_migration/converters/policy/zone_based_firewall.py, catalystwan/utils/config_migration/creators/config_pusher.py, catalystwan/utils/config_migration/creators/groups_of_interests_pusher.py, catalystwan/workflows/config_migration.py
Multiple fixes for config migration
=> dev: converter fixes

ENDPOINTS.md, catalystwan/models/configuration/feature_profile/sdwan/application_priority/traffic_policy.py, catalystwan/models/configuration/feature_profile/sdwan/service/lan/ethernet.py, catalystwan/tests/config_migration/test_transform.py, catalystwan/utils/config_migration/converters/policy/centralized_policy.py, catalystwan/utils/config_migration/converters/policy/policy_settings.py, catalystwan/utils/config_migration/creators/localized_policy_pusher.py, catalystwan/utils/config_migration/reverters/config_reverter.py, catalystwan/utils/config_migration/steps/constants.py, catalystwan/workflows/config_migration.py, pyproject.toml
config migration fixes for 20.12
- Fix ethernet model
- Add rollbacking policy groups
- Mark policy settings as unsupported for 20.12
- Dont create SVI interface for transport and management feature profile
=> dev: config migration fixes for 20.12

catalystwan/endpoints/configuration_settings.py
Add configuration settings endpoint for Enterprise Root CA
Provides possibility of configuring Enterprise Root CA at `Administration Settings/Trust and Privacy/Controller Certificate Authorization`
=> Add configuration settings endpoint for enterprise root certificate

ENDPOINTS.md, catalystwan/endpoints/configuration/policy/vsmart_template.py, pyproject.toml
activate/deactivate id string returned by server is not UUID (contains custom prefix)
=> fix: vsmart template activate/deactivate response validation

ENDPOINTS.md, catalystwan/apigw_auth.py, catalystwan/response.py, catalystwan/session.py, catalystwan/tests/test_vmanage_auth.py, catalystwan/vmanage_auth.py, pyproject.toml
vManageAuth refactor
- fix `409` when `VSessionId` was not properly refreshed after `JSESSIONID` updated
- fix infinite auth loop when `vAnalytics` enabled
- `VSessionId` flow for `provider-as-tenant` is now separate `AuthBase` class instead part of `login()` method
=> auth: refactor

catalystwan/endpoints/cluster_management.py
Fix `get_connected_devices` endpoint
`get_connected_devices` endpoint response can contain vEdge devices. Those devices can have a uuid, that does not fit the standard hexadecimal uuid format, i.e.:
`C8K-220291CC-2003-3CDA-FDDA-F24D9E7B4B89`
This leads to SDK throwing a ValueError.
This PR changes UUID to basic string to avoid that.
=> fix get_connected_devices endpoint

README.md, catalystwan/abstractions.py, catalystwan/apigw_auth.py, catalystwan/request_limiter.py, catalystwan/session.py, catalystwan/vmanage_auth.py, pyproject.toml
Adds support for multithreading authentication, which allows for concurrent requests using the same auth.
```python
from threading import Thread
from catalystwan.session import ManagerSession
from catalystwan.vmanage_auth import vManageAuth
from copy import copy
def print_devices(manager: ManagerSession):
with manager.login() as session:
print(session.api.devices.get())
if __name__ =="__main__":
auth = vManageAuth(username="username", password="password")
manager = ManagerSession(base_url="https://url:port", auth=auth)
t1 = Thread(target=print_devices, args=(manager,))
t2 = Thread(target=print_devices, args=(copy(manager),))
t3 = Thread(target=print_devices, args=(copy(manager),))
t1.start()
t2.start()
t3.start()
t1.join()
t2.join()
t3.join()
print("Done!")
```
=> Multithreading Auth

catalystwan/models/configuration/feature_profile/sdwan/uc_voice/dsp_farm.py, pyproject.toml
=> dev: Fix dsp_farm model_config populate_by_name

catalystwan/api/mtt_aaa_api.py, pyproject.toml
add support for tenant level user to make API calls for mtt aaa.
currently only provider as a tenant user is able to make API calls because there are provider level calls in the existing classes that are forbidden for tenant level users.
i have added 2 more classes, where we don't invoke provider level APIs.
So tenant level users can add tacacs or radius servers
=> add support for tenant level user to make API calls for mtt aaa
