catalystwan/api/policy_api.py, catalystwan/endpoints/configuration/policy/list/trunkgroup.py, catalystwan/endpoints/endpoints_container.py, catalystwan/models/policy/__init__.py, catalystwan/models/policy/list/trunkgroup.py
introduce trunkgroup policy list
=> introduce trunkgroup policy list

catalystwan/models/configuration/feature_profile/sdwan/policy_object/__init__.py, catalystwan/models/configuration/feature_profile/sdwan/policy_object/security/intrusion_prevention.py
Intrusion prevention model
Intrusion prevention model
=> Intrusion prevention model

catalystwan/models/configuration/feature_profile/sdwan/policy_object/security/url_filtering.py
URL Filtering model
URL Filtering model
=> URL Filtering model

.pre-commit-config.yaml, catalystwan/api/policy_api.py, catalystwan/endpoints/configuration/policy/list/threat_grid_api_key.py, catalystwan/models/policy/__init__.py, catalystwan/models/policy/list/threat_grid_api_key.py
Introduce Threat grid API key list
=> Threat grid api key list

catalystwan/api/policy_api.py, catalystwan/endpoints/configuration/policy/definition/amp.py, catalystwan/models/policy/__init__.py, catalystwan/models/policy/definition/amp.py
Introducing advanced malware protection model (v1 api)
=> Advanced malware protection v1

catalystwan/api/feature_profile_api.py, catalystwan/endpoints/configuration/feature_profile/sdwan/other.py, catalystwan/endpoints/configuration/feature_profile/sdwan/policy_object.py, catalystwan/endpoints/configuration/feature_profile/sdwan/service.py, catalystwan/endpoints/configuration/feature_profile/sdwan/system.py, catalystwan/endpoints/configuration/feature_profile/sdwan/transport.py, catalystwan/endpoints/configuration_group.py, catalystwan/models/configuration/config_migration.py, catalystwan/models/configuration/feature_profile/common.py, catalystwan/models/configuration/feature_profile/parcel.py, catalystwan/tests/test_feature_profile_api.py, catalystwan/utils/config_migration/converters/feature_template/ospfv3.py, endpoints-md.py
- Support type hinting for get_parcels and get_parcel
- Move Parcel related classes to one file
- Add endpoint for system parcels with typing
=> dev-uxmt: System Feature Profile API type hinting

catalystwan/api/config_group_api.py, catalystwan/api/policy_api.py, catalystwan/endpoints/configuration/policy/security_template.py, catalystwan/endpoints/configuration_group.py, catalystwan/models/configuration/feature_profile/sdwan/policy_object/policy/as_path.py, catalystwan/models/policy/definition/amp.py, catalystwan/models/policy/definition/zone_based_firewall.py, catalystwan/models/policy/policy_definition.py, catalystwan/models/policy/security.py, catalystwan/utils/config_migration/converters/policy/policy_lists.py, catalystwan/workflows/config_migration.py, pyproject.toml
multiple minor fixes and improvements:
- fix policy list / parcel models
- refactor policy list converter
- fix config group api
=> dev-uxmt: multiple minor fixes and improvements

catalystwan/api/configuration_groups/parcel.py, catalystwan/models/common.py, catalystwan/tests/test_endpoints.py, catalystwan/tests/test_models_common.py
- extract model field iterator from serialization logic in `dump` method.
- allow usage with `_ParcelBase` custom serializer
=> dev-uxmt: versioned field improvements

catalystwan/integration_tests/feature_profile/sdwan/test_transport.py, catalystwan/models/configuration/feature_profile/sdwan/transport/__init__.py, catalystwan/models/configuration/feature_profile/sdwan/transport/t1e1controller.py, catalystwan/tests/test_feature_profile_api.py
- Add model. 
- Add unit test. 
- Add integration test
=> E1T1Controller

catalystwan/api/configuration_groups/parcel.py, catalystwan/models/configuration/feature_profile/sdwan/policy_object/policy/expanded_community_list.py, catalystwan/models/configuration/feature_profile/sdwan/service/appqoe.py, catalystwan/models/configuration/feature_profile/sdwan/service/route_policy.py, catalystwan/models/configuration/feature_profile/sdwan/system/aaa.py, pyproject.toml
enhance as_global, as_default, fix models
=> enhance as_global, as_default

catalystwan/api/policy_api.py, catalystwan/endpoints/configuration/policy/definition/intrusion_prevention.py, catalystwan/models/common.py, catalystwan/models/policy/__init__.py, catalystwan/models/policy/definition/amp.py, catalystwan/models/policy/definition/intrusion_prevention.py
Introducing Intrusion prevention v1 model
=> Intrusion prevention v1 model

catalystwan/integration_tests/feature_profile/sdwan/test_system.py, catalystwan/integration_tests/feature_profile/sdwan/test_transport.py, catalystwan/models/configuration/feature_profile/sdwan/transport/vpn_management.py, catalystwan/session.py, catalystwan/tests/templates/test_serialize_model.py, catalystwan/tests/test_templates.py, catalystwan/utils/config_migration/converters/feature_template/multicast.py
Fix incorrect values for as_default method
Replace deprecated method parse_obj by model_validate Remove duplicated records after test
=> Fix all unitests

catalystwan/models/configuration/feature_profile/sdwan/system/aaa.py
Default value for user privilege is 15.
=> UX2.0 AAAParcel UserItem: fix default value for privilege

catalystwan/api/policy_api.py, catalystwan/endpoints/configuration/policy/definition/aip.py, catalystwan/models/policy/__init__.py, catalystwan/models/policy/definition/aip.py
Introducing Advanced Profile Inspection v1 model
=> Advanced Inspection Profile v1 model

catalystwan/models/configuration/feature_profile/sdwan/system/bfd.py
Default values in BDFParcel model was set as global instead as default.
=> UX2.0 Fix default value in BFDParcel model.

catalystwan/api/config_group_api.py, catalystwan/endpoints/configuration_group.py, catalystwan/integration_tests/feature_profile/sdwan/test_system.py, catalystwan/models/configuration/feature_profile/sdwan/system/aaa.py
Add method add_user() and set_server_auth_order() to AAAParcel.
=> UX2.0 Add new methods to AAAParcel.

catalystwan/api/feature_profile_api.py, catalystwan/endpoints/configuration/feature_profile/sdwan/embedded_security.py, catalystwan/models/configuration/feature_profile/common.py, catalystwan/models/configuration/feature_profile/parcel.py, catalystwan/models/configuration/feature_profile/sdwan/embedded_security/__init__.py, catalystwan/models/configuration/feature_profile/sdwan/embedded_security/ngfirewall.py, catalystwan/models/configuration/feature_profile/sdwan/embedded_security/policy.py
Embedded Security
Embedded Security
=> dev-uxmt: Embedded Security

catalystwan/integration_tests/feature_profile/sdwan/test_transport.py, catalystwan/models/configuration/feature_profile/sdwan/transport/__init__.py, catalystwan/models/configuration/feature_profile/sdwan/transport/wan/interface/protocol_over.py, catalystwan/utils/config_migration/converters/feature_template/base.py, catalystwan/utils/config_migration/converters/feature_template/parcel_factory.py, catalystwan/utils/config_migration/converters/feature_template/protocol_over.py, catalystwan/workflows/config_migration.py
- Add model ipoe. 
- Add converter. 
- Add integration test
=> Add model ipoe. Add converter. Add integration test

catalystwan/api/feature_profile_api.py, catalystwan/endpoints/configuration/feature_profile/sdwan/dns_security.py, catalystwan/integration_tests/feature_profile/sdwan/base.py, catalystwan/integration_tests/feature_profile/sdwan/test_dns_security.py, catalystwan/models/configuration/feature_profile/parcel.py, catalystwan/models/configuration/feature_profile/sdwan/dns_security/__init__.py, catalystwan/models/configuration/feature_profile/sdwan/dns_security/dns.py
DNS Security parcel
DNS Security parcel
=> dev-uxmt: DNS Security parcel

catalystwan/api/policy_api.py, catalystwan/endpoints/configuration/policy/definition/dns_security.py, catalystwan/endpoints/configuration/policy/list/umbrella_data.py, catalystwan/models/policy/__init__.py, catalystwan/models/policy/definition/dns_security.py, catalystwan/models/policy/list/umbrella_data.py
Introducing DNS Security and Umbrella Data policy V1 models
=> Introducing DNS Security and Umbrella data v1 models

catalystwan/models/policy/definition/rewrite.py, catalystwan/models/policy/definition/rule_set.py, catalystwan/models/policy/localized.py, catalystwan/models/policy/policy.py
Fixing v1 models, basing on examples configuiration sets
=> Models improvements basing on example configuration

catalystwan/integration_tests/feature_profile/sdwan/test_service.py, catalystwan/integration_tests/feature_profile/sdwan/test_transport.py, catalystwan/models/common.py, catalystwan/models/configuration/feature_profile/common.py, catalystwan/models/configuration/feature_profile/sdwan/service/bgp.py, catalystwan/models/configuration/feature_profile/sdwan/service/eigrp.py, catalystwan/models/configuration/feature_profile/sdwan/service/lan/common.py, catalystwan/models/configuration/feature_profile/sdwan/service/lan/gre.py, catalystwan/models/configuration/feature_profile/sdwan/service/lan/ipsec.py, catalystwan/models/configuration/feature_profile/sdwan/service/lan/vpn.py, catalystwan/models/configuration/feature_profile/sdwan/service/ospfv3.py, catalystwan/models/configuration/feature_profile/sdwan/transport/__init__.py, catalystwan/models/configuration/feature_profile/sdwan/transport/wan/interface/gre.py, catalystwan/models/configuration/feature_profile/sdwan/transport/wan/interface/ipsec.py, catalystwan/models/configuration/feature_profile/sdwan/transport/wan/interface/protocol_over.py, catalystwan/models/configuration/feature_profile/sdwan/transport/wan/interface/t1e1serial.py, catalystwan/tests/test_feature_profile_api.py, catalystwan/utils/config_migration/converters/feature_template/eigrp.py, catalystwan/utils/config_migration/converters/feature_template/helpers.py, catalystwan/utils/config_migration/converters/feature_template/lan/gre.py, catalystwan/utils/config_migration/converters/feature_template/lan/ipsec.py, catalystwan/utils/config_migration/converters/feature_template/normalizer.py, catalystwan/utils/config_migration/converters/feature_template/ospfv3.py, catalystwan/utils/config_migration/converters/feature_template/parcel_factory.py, catalystwan/utils/config_migration/converters/feature_template/vpn.py, catalystwan/utils/config_migration/converters/feature_template/wan/gre.py, catalystwan/utils/config_migration/converters/feature_template/wan/ipsec.py, catalystwan/utils/config_migration/converters/feature_template/wan/protocol_over.py, catalystwan/utils/config_migration/converters/feature_template/wan/t1e1serial.py
- Add Wan Ipsec model
- Add integration test
- Change the name of common model Prefix to AddressWithMask
- Move more literals to common
- Add unit tests for post for wan interfaces
=> Add Wan Ipsec

catalystwan/api/configuration_groups/parcel.py, catalystwan/integration_tests/feature_profile/sdwan/test_transport.py, catalystwan/models/configuration/feature_profile/common.py, catalystwan/models/configuration/feature_profile/parcel.py, catalystwan/models/configuration/feature_profile/sdwan/transport/wan/interface/cellular.py, catalystwan/models/configuration/feature_profile/sdwan/transport/wan/interface/protocol_over.py, catalystwan/models/configuration/feature_profile/sdwan/transport/wan/interface/t1e1serial.py, catalystwan/tests/test_feature_profile_api.py, catalystwan/utils/config_migration/converters/feature_template/parcel_factory.py, catalystwan/utils/config_migration/converters/feature_template/wan/cellular.py, catalystwan/utils/config_migration/converters/feature_template/wan/protocol_over.py, catalystwan/utils/config_migration/converters/feature_template/wan/t1e1serial.py
- Add Cellular Interface. 
- Add converter. 
- Add unit test. 
- Add integration test. 
- Move more models to common
- Now as_default() can take None and produce correct instance
`as_default(None) -> Default[None](value=None) `
=> Add Cellular Interface. 

catalystwan/integration_tests/feature_profile/sdwan/test_transport.py, catalystwan/models/configuration/feature_profile/parcel.py, catalystwan/models/configuration/feature_profile/sdwan/transport/__init__.py, catalystwan/models/configuration/feature_profile/sdwan/transport/gps.py, catalystwan/tests/test_feature_profile_api.py, catalystwan/utils/config_migration/converters/feature_template/gps.py, catalystwan/utils/config_migration/converters/feature_template/parcel_factory.py
=> Add gps parcel and converter.

catalystwan/integration_tests/feature_profile/sdwan/test_transport.py, catalystwan/models/configuration/feature_profile/sdwan/transport/__init__.py, catalystwan/models/configuration/feature_profile/sdwan/transport/cellular_profile.py, catalystwan/tests/test_feature_profile_api.py, catalystwan/utils/config_migration/converters/feature_template/cellular_profile.py, catalystwan/utils/config_migration/converters/feature_template/parcel_factory.py
- Add cellular-profile. 
- Add converter
=> Add cellular-profile. Add converter

catalystwan/models/policy/__init__.py, catalystwan/models/policy/definition/access_control_list.py, catalystwan/models/policy/definition/access_control_list_ipv6.py, catalystwan/models/policy/definition/control.py, catalystwan/models/policy/definition/device_access.py, catalystwan/models/policy/definition/device_access_ipv6.py, catalystwan/models/policy/definition/traffic_data.py, catalystwan/models/policy/definition/zone_based_firewall.py, catalystwan/models/policy/policy_definition.py
Spliting DefaultAction into new types
=> Spliting DefaultAction into new types

catalystwan/utils/config_migration/factories/feature_profile_api.py, catalystwan/utils/config_migration/reverters/config_reverter.py
=> Add Cli api to feature profile factory, improve reverter

catalystwan/api/policy_api.py, catalystwan/endpoints/configuration/policy/definition/ssl_decryption.py, catalystwan/models/common.py, catalystwan/models/policy/__init__.py, catalystwan/models/policy/definition/access_control_list.py, catalystwan/models/policy/definition/access_control_list_ipv6.py, catalystwan/models/policy/definition/device_access.py, catalystwan/models/policy/definition/device_access_ipv6.py, catalystwan/models/policy/definition/ssl_decryption.py, catalystwan/models/policy/definition/traffic_data.py, catalystwan/models/policy/definition/zone_based_firewall.py, catalystwan/models/policy/policy_definition.py
Introducing SSL Decryption v1 model
=> SSL decryption v1 model

catalystwan/api/feature_profile_api.py, catalystwan/endpoints/configuration/feature_profile/sdwan/sig_security.py, catalystwan/endpoints/configuration_settings.py, catalystwan/endpoints/endpoints_container.py, catalystwan/integration_tests/feature_profile/sdwan/base.py, catalystwan/integration_tests/feature_profile/sdwan/test_sig_security.py, catalystwan/models/configuration/config_migration.py, catalystwan/models/configuration/feature_profile/common.py, catalystwan/models/configuration/feature_profile/parcel.py, catalystwan/models/configuration/feature_profile/sdwan/dns_security/dns.py, catalystwan/models/configuration/feature_profile/sdwan/sig_security/__init__.py, catalystwan/models/configuration/feature_profile/sdwan/sig_security/sig_security.py, catalystwan/utils/config_migration/converters/feature_template/cloud_credentials.py, catalystwan/utils/config_migration/converters/feature_template/parcel_factory.py, catalystwan/utils/config_migration/converters/feature_template/sig.py, catalystwan/utils/config_migration/creators/config_pusher.py, catalystwan/workflows/config_migration.py
Add SIGParcel model and converersion of SIG/SIG Credentials
=> Added SIG model and converter

catalystwan/api/feature_profile_api.py, catalystwan/endpoints/configuration/feature_profile/sdwan/application_priority.py, catalystwan/integration_tests/feature_profile/sdwan/base.py, catalystwan/integration_tests/feature_profile/sdwan/test_application_priority.py, catalystwan/models/configuration/feature_profile/parcel.py, catalystwan/models/configuration/feature_profile/sdwan/application_priority/__init__.py, catalystwan/models/configuration/feature_profile/sdwan/application_priority/policy_settings.py, catalystwan/models/configuration/feature_profile/sdwan/application_priority/qos_policy.py
Policy settings parcel and QoS policy model
Policy settings parcel and QoS policy model
=> dev-uxmt: Policy settings parcel and QoS policy model

catalystwan/integration_tests/feature_profile/sdwan/test_transport.py, catalystwan/models/common.py, catalystwan/models/configuration/feature_profile/common.py, catalystwan/models/configuration/feature_profile/parcel.py, catalystwan/models/configuration/feature_profile/sdwan/service/lan/common.py, catalystwan/models/configuration/feature_profile/sdwan/service/lan/ethernet.py, catalystwan/models/configuration/feature_profile/sdwan/service/lan/svi.py, catalystwan/models/configuration/feature_profile/sdwan/service/switchport.py, catalystwan/models/configuration/feature_profile/sdwan/transport/__init__.py, catalystwan/models/configuration/feature_profile/sdwan/transport/wan/interface/ethernet.py, catalystwan/models/configuration/feature_profile/sdwan/transport/wan/interface/protocol_over.py, catalystwan/tests/config_migration/models/__init__.py, catalystwan/tests/config_migration/models/feature_templates/interface.py, catalystwan/tests/config_migration/models/feature_templates/malformed.py, catalystwan/tests/config_migration/models/feature_templates/vpn.py, catalystwan/tests/config_migration/test_transform.py, catalystwan/utils/config_migration/converters/feature_template/lan/ethernet.py, catalystwan/utils/config_migration/converters/feature_template/lan/svi.py, catalystwan/utils/config_migration/converters/feature_template/normalizer.py, catalystwan/utils/config_migration/converters/feature_template/parcel_factory.py, catalystwan/utils/config_migration/converters/feature_template/wan/ethernet.py, catalystwan/utils/config_migration/steps/constants.py, catalystwan/utils/config_migration/steps/transform.py, catalystwan/utils/feature_template/find_template_values.py, catalystwan/workflows/config_migration.py
- Add Wan Ethernet Interface
- Move as much as possible models to common (Wan Ethernet, Lan Ethernet)
- Add Intergration test
- Add unit test that checks if Ethernet interfaces are in correct Feature Profiles after transform (Ethernet Feature Templates can create 3 parcels: WAN, LAN, MANAGEMENT interface ethernet parcel)
- Move models from unit test to seperate file to be reusable
=> dev-uxmt: Add wan ethernet model. Move more model to common. Add integration test

catalystwan/api/policy_api.py, catalystwan/endpoints/configuration/policy/definition/route_policy.py, catalystwan/models/common.py, catalystwan/models/policy/__init__.py, catalystwan/models/policy/definition/access_control_list.py, catalystwan/models/policy/definition/access_control_list_ipv6.py, catalystwan/models/policy/definition/control.py, catalystwan/models/policy/definition/route_policy.py, catalystwan/models/policy/definition/traffic_data.py, catalystwan/models/policy/policy_definition.py
Introducing route policy v1 model
=> RoutePolicy model (UX1)

catalystwan/models/configuration/feature_profile/common.py, catalystwan/workflows/config_migration.py
=> dev-uxmt: Fix typo

.pre-commit-config.yaml, catalystwan/api/policy_api.py, catalystwan/endpoints/configuration/policy/list/extended_community.py, catalystwan/models/policy/__init__.py, catalystwan/models/policy/list/communities.py
Introducing advanced community list v1 model
Upgrading flake8 to 7.0.0
=> Extended community list v1 model

catalystwan/api/feature_profile_api.py, catalystwan/integration_tests/feature_profile/sdwan/test_transport.py, catalystwan/models/configuration/feature_profile/parcel.py, catalystwan/models/configuration/feature_profile/sdwan/transport/__init__.py, catalystwan/models/configuration/feature_profile/sdwan/transport/management/ethernet.py, catalystwan/tests/config_migration/test_transform.py, catalystwan/tests/test_normalize_to_model_definition.py, catalystwan/utils/config_migration/converters/feature_template/ethernet.py, catalystwan/utils/config_migration/converters/feature_template/model_definition_normalizer.py, catalystwan/utils/config_migration/converters/feature_template/parcel_factory.py, catalystwan/workflows/config_migration.py
Adds management interface ethernet parcel
=> Added Management Ethernet model

catalystwan/models/configuration/config_migration.py, catalystwan/utils/config_migration/creators/config_pusher.py
=> dev-uxmt: Cover exceptions in config push - always return report

catalystwan/api/feature_profile_api.py, catalystwan/integration_tests/feature_profile/sdwan/test_extended_community.py, catalystwan/models/configuration/feature_profile/parcel.py, catalystwan/models/configuration/feature_profile/sdwan/policy_object/__init__.py, catalystwan/models/configuration/feature_profile/sdwan/policy_object/policy/extended_community.py
Introducing extended community list parcel
=> Extended community parcel

catalystwan/api/builders/feature_profiles/report.py, catalystwan/api/feature_profile_api.py, catalystwan/endpoints/__init__.py, catalystwan/endpoints/configuration/feature_profile/sdwan/policy_object.py, catalystwan/models/configuration/config_migration.py, catalystwan/models/configuration/feature_profile/common.py, catalystwan/models/configuration/feature_profile/parcel.py, catalystwan/models/configuration/feature_profile/sdwan/policy_object/__init__.py, catalystwan/models/configuration/feature_profile/sdwan/policy_object/policy/expanded_community_list.py, catalystwan/models/configuration/feature_profile/sdwan/policy_object/policy/sla_class.py, catalystwan/models/policy/list/app.py, catalystwan/utils/config_migration/converters/policy/policy_lists.py, catalystwan/utils/config_migration/creators/config_pusher.py, catalystwan/utils/config_migration/reverters/config_reverter.py, catalystwan/utils/model.py, catalystwan/workflows/config_migration.py
Implement push and rollback for policy "Groups of Interest" which are UX1 Policy Lists and Policy Definitions transformed into Policy Object Parcels and pushed to system-generated Policy Object Profile.
=> dev-uxmt: groups of interest push

catalystwan/integration_tests/feature_profile/sdwan/test_system.py, catalystwan/models/configuration/feature_profile/sdwan/system/__init__.py, catalystwan/models/configuration/feature_profile/sdwan/system/device_access.py, catalystwan/models/configuration/feature_profile/sdwan/system/device_access_ipv6.py, catalystwan/utils/type_check.py
Add device access parcel models
=> dev-uxmt: Add Device Access parcel models

catalystwan/models/configuration/feature_profile/sdwan/policy_object/policy/mirror.py, catalystwan/tests/test_mirror_converter.py, catalystwan/utils/config_migration/converters/policy/policy_lists.py
=> dev-uxmt: MirrorList converter

catalystwan/endpoints/configuration/feature_profile/sdwan/application_priority.py, catalystwan/endpoints/configuration/feature_profile/sdwan/dns_security.py, catalystwan/endpoints/configuration/feature_profile/sdwan/embedded_security.py, catalystwan/endpoints/configuration/feature_profile/sdwan/policy_object.py, catalystwan/endpoints/configuration/feature_profile/sdwan/topology.py, catalystwan/endpoints/configuration/feature_profile/sdwan/transport.py, catalystwan/endpoints/configuration_feature_profile.py, catalystwan/integration_tests/profile_builder/test_pb_service.py, catalystwan/tests/config_migration/test_normalizer.py, catalystwan/utils/config_migration/converters/feature_template/normalizer.py, catalystwan/utils/config_migration/creators/config_pusher.py
=> Change version of endpoints to 20.12, handle incompatibile variable str

catalystwan/tests/config_migration/test_transform.py, catalystwan/utils/config_migration/steps/transform.py, catalystwan/workflows/config_migration.py
=> Remove duplicated feature templates, add unit test

catalystwan/tests/config_migration/test_transform.py, catalystwan/utils/config_migration/steps/transform.py, catalystwan/workflows/config_migration.py
=> Change logic to remove all unused templates, not only copied

catalystwan/integration_tests/feature_profile/sdwan/test_extended_community.py, catalystwan/models/configuration/feature_profile/sdwan/policy_object/policy/extended_community.py, catalystwan/tests/test_extended_community_converter.py, catalystwan/utils/config_migration/converters/policy/policy_lists.py
Indtroducing extended community converter
=> Extended community list converter

catalystwan/models/configuration/config_migration.py, catalystwan/utils/config_migration/steps/transform.py, catalystwan/workflows/config_migration.py
=> dev-uxmt: Bugfix: remove standalone feature templates. 

catalystwan/integration_tests/feature_profile/sdwan/test_service.py, catalystwan/models/configuration/feature_profile/sdwan/service/lan/ethernet.py, catalystwan/utils/config_migration/converters/feature_template/lan/ethernet.py
When we send advanced.intrfMtu as Default 1500 we get 400. UI also dont send any value
```
{
"parcelName": "vedge-C8000V_interface_*GigabitEthernet3.2*_FT_84.xml_84fa5_SERVICE",
"parcelType": "lan/vpn/interface/ethernet",
"errorInfo": {
"message": "Invalid Payload",
"details": "Invalid Payload: doesn't support user settable interface mtu for sub interface",
"code": "PPARC0012"
},
"failedRequest": {
"method": "POST",
"url": "https://172.22.219.75:9912/dataservice/v1/feature-profile/sdwan/service/c19f52d0-edbe-4d40-bb1d-38491269e1a5/lan/vpn/3eccca45-41e6-4a83-9da5-561a10adeddf/interface/ethernet",
"headers": "{'User-Agent': 'catalystwan/0.33.4.dev0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'content-type': 'application/json', 'Cookie': …
```
=> dev-uxmt: hotfix: model lan ethernet interface

catalystwan/utils/config_migration/converters/policy/policy_lists.py
remove from converter list for now
=> dev-uxmt: as-path is unsupported

catalystwan/tests/test_vmanage_auth.py, catalystwan/vmanage_auth.py
In same case this token can be html login page and raise incorrect error in future login flow.
=> Validate XSRF token returned by server

ENDPOINTS.md, pyproject.toml
=> dev-uxmt: bump dev 0.33.7dev5

catalystwan/models/configuration/config_migration.py, catalystwan/models/configuration/feature_profile/sdwan/policy_object/security/amp.py, catalystwan/tests/test_amp_converter.py, catalystwan/utils/config_migration/converters/policy/policy_definitions.py, catalystwan/workflows/config_migration.py
Introducing Advanced Malware Protection converter
=> dev-uxmt: Advanced Malware Protection converter

catalystwan/tests/test_typed_list.py, catalystwan/typed_list.py
Add copy and deepcopy implementation to DataSequence
#63
=> Add copy and deepcopy

catalystwan/utils/reachability.py
Add default value for Reachability
#691
=> Fix get_devices_health()

catalystwan/api/configuration_groups/parcel.py, catalystwan/models/configuration/config_migration.py, catalystwan/models/configuration/feature_profile/common.py, catalystwan/models/configuration/feature_profile/sdwan/dns_security/dns.py, catalystwan/tests/config_migration/policy_converters/test_dns_security_converter.py, catalystwan/utils/config_migration/converters/policy/policy_definitions.py, catalystwan/utils/config_migration/creators/config_pusher.py, catalystwan/utils/config_migration/creators/groups_of_interests_pusher.py, catalystwan/utils/config_migration/creators/policy_object_pusher.py, catalystwan/utils/config_migration/creators/references_updater.py, catalystwan/utils/config_migration/creators/security_policy_pusher.py, catalystwan/utils/config_migration/factories/feature_profile_api.py, catalystwan/utils/config_migration/runner.py
Introducing DNS Security group conversion
=> DNS security group conversion

catalystwan/endpoints/configuration_settings.py
Fields: validityPeriod and retrieveInterval in Certificate should be optional
=> Issues/698 Fields: validityPeriod and retrieveInterval in Certificate

catalystwan/models/common.py, catalystwan/models/configuration/feature_profile/sdwan/acl/ipv4acl.py, catalystwan/models/configuration/feature_profile/sdwan/acl/ipv6acl.py, catalystwan/models/policy/definition/access_control_list.py, catalystwan/models/policy/definition/access_control_list_ipv6.py, catalystwan/models/policy/definition/traffic_data.py, catalystwan/models/policy/policy_definition.py, catalystwan/tests/config_migration/policy_converters/test_acl_ipv4.py, catalystwan/tests/config_migration/policy_converters/test_acl_ipv6.py, catalystwan/utils/config_migration/converters/policy/policy_definitions.py
`acl-ipv4` improve models, converter, tests
`acl-ipv6` improve models, converter, tests
=> dev-uxmt: acl improvements

catalystwan/models/configuration/config_migration.py, catalystwan/models/configuration/feature_profile/common.py, catalystwan/models/configuration/feature_profile/parcel.py, catalystwan/models/configuration/feature_profile/sdwan/embedded_security/ngfirewall.py, catalystwan/models/policy/definition/rule_set.py, catalystwan/models/policy/definition/ssl_decryption.py, catalystwan/models/policy/definition/traffic_data.py, catalystwan/models/policy/definition/zone_based_firewall.py, catalystwan/models/policy/policy.py, catalystwan/models/policy/policy_definition.py, catalystwan/models/policy/security.py, catalystwan/tests/config_migration/policy_converters/test_zone_based_firewall_converter.py, catalystwan/utils/config_migration/converters/policy/policy_definitions.py, catalystwan/utils/config_migration/converters/policy/zone_based_firewall.py
Introducing ZoneBasedFirewall converter
=> NG firewall conversion

catalystwan/api/configuration_groups/parcel.py, catalystwan/models/configuration/feature_profile/sdwan/embedded_security/policy.py, catalystwan/models/configuration/feature_profile/sdwan/policy_object/security/url_filtering.py, catalystwan/tests/config_migration/policy_converters/test_references_updater.py, catalystwan/utils/config_migration/creators/groups_of_interests_pusher.py, catalystwan/utils/config_migration/creators/references_updater.py, catalystwan/utils/config_migration/creators/security_policy_pusher.py
Removing dedicated parcels references updates and creating generic one
=> Generic parcels references updater

catalystwan/models/policy/policy.py, catalystwan/models/policy/security.py, catalystwan/tests/config_migration/policy_converters/test_security_policy_converter.py
Adding security policy conversion UTs
=> SecurityPolicy convert unit tests

ENDPOINTS.md, catalystwan/models/configuration/feature_profile/sdwan/dns_security/dns.py, catalystwan/utils/config_migration/runner.py, pyproject.toml
=> dev-uxmt: migration runner filter dt by pattern

ENDPOINTS.md, catalystwan/models/configuration/config_migration.py, pyproject.toml
use alias generator for config-migration workflow models:
- consistent public api (camelCase alias is automatically generated)
- definitions are less cluttered
=> dev-uxmt: model cleanup for config migration workflow 

catalystwan/api/builders/feature_profiles/application_priority.py, catalystwan/api/builders/feature_profiles/builder_factory.py, catalystwan/models/configuration/config_migration.py, catalystwan/models/configuration/feature_profile/common.py, catalystwan/models/configuration/feature_profile/sdwan/application_priority/qos_policy.py, catalystwan/models/policy/definition/qos_map.py, catalystwan/models/policy/localized.py, catalystwan/models/policy/policy.py, catalystwan/tests/config_migration/policy_converters/test_qos_map_converter.py, catalystwan/tests/config_migration/test_data/__init__.py, catalystwan/tests/config_migration/test_data/localized_policies/localized_policy.py, catalystwan/tests/config_migration/test_data/policy_definitions/qos_map.py, catalystwan/tests/config_migration/test_transform.py, catalystwan/utils/config_migration/converters/policy/policy_definitions.py, catalystwan/utils/config_migration/converters/policy/policy_settings.py, catalystwan/utils/config_migration/creators/config_pusher.py, catalystwan/utils/config_migration/creators/localized_policy_pusher.py, catalystwan/utils/config_migration/creators/security_policy_pusher.py, catalystwan/utils/config_migration/factories/feature_profile_api.py, catalystwan/workflows/config_migration.py
- Add qos map converter
- Add localized policy settings converter
- Add code that pushes converted items
=> dev-uxmt: Qos map conversion

ENDPOINTS.md, pyproject.toml
=> release: 0.34.0

.github/workflows/integrationtests.yml
=> Run integration tests on dev branch

catalystwan/api/builders/feature_profiles/report.py
=> Remove headers from failed parcel

catalystwan/api/configuration_groups/parcel.py, catalystwan/integration_tests/feature_profile/sdwan/topology/test_topology.py, catalystwan/models/common.py, catalystwan/models/configuration/config_migration.py, catalystwan/models/configuration/feature_profile/sdwan/topology/custom_control.py, catalystwan/utils/config_migration/converters/policy/centralized_policy.py, catalystwan/utils/config_migration/converters/policy/policy_definitions.py
=> dev: fix custom-control

.github/workflows/linting.yml, .github/workflows/release.yml, .github/workflows/unittests.yml
Fix https://github.com/cisco-open/cisco-catalyst-wan-sdk/security/code-scanning/22
=> pin github action versions

pyproject.toml
=> bump version 

pyproject.toml
Bump version
Bump version 0.34.0dev5
=> Bump version 0.34.0dev5

README.md, catalystwan/api/administration.py, catalystwan/api/tenant_management_api.py, catalystwan/apigw_auth.py, catalystwan/endpoints/api_gateway.py, catalystwan/response.py, catalystwan/session.py, catalystwan/tests/test_administration.py, catalystwan/tests/test_devices_api.py, catalystwan/tests/test_session.py, catalystwan/tests/test_tenant_management_api.py, catalystwan/tests/test_vmanage_auth.py, catalystwan/vmanage_auth.py, catalystwan/workflows/tenant_migration.py, pyproject.toml
Implement api gw login
```python
from catalystwan.session import create_apigw_session
with create_apigw_session(
url="example.com",
client_id="client_id",
client_secret="client_secret",
org_name="Org-Name",
username="user",
mode="user",
token_duration=10,
) as session:
devices = session.api.devices.get()
print(devices)
```
=> Add API GW login. Refactor session related files.

.github/workflows/linting.yml, .github/workflows/release.yml, .github/workflows/unittests.yml, ENDPOINTS.md, catalystwan/api/templates/cli_template.py, catalystwan/apigw_auth.py, catalystwan/endpoints/configuration/policy/vsmart_template.py, catalystwan/vmanage_auth.py, catalystwan/workflows/tenant_migration.py, pyproject.toml
Apply changes from `main` to `dev` branch (since `0.34.0` to `0.35.0`)
Bump dev version to `0.35.0dev0`
=> dev: sync with 0.35.0

catalystwan/models/configuration/feature_profile/sdwan/service/lan/ethernet.py, pyproject.toml
=> dev: fix field aliases for lan/ethernet parcel

ENDPOINTS.md, catalystwan/api/admin_tech_api.py, catalystwan/api/task_status_api.py, catalystwan/api/template_api.py, pyproject.toml
Added extra info about validation activities when TaskValidationError is raised
Validation Activities added to be printed whenever TasKValidationError is raised. Currently only the STATUS is reported, which is not enough to understand the real reason.
=> Added extra info about validation activities when TaskValidationError is raised

catalystwan/models/policy/localized.py, catalystwan/models/policy/policy_definition.py, pyproject.toml
=> Fix collecting RoutePolicyGetResponse and LocalizedPolicyInfo

catalystwan/endpoints/certificate_management_device.py
Add Changing certificate validity to 'staging' in endpoints.certificate_management_device.py
=> Add staging

catalystwan/models/configuration/feature_profile/sdwan/service/lan/ethernet.py, pyproject.toml
=> dev: fix trustsec defaults

catalystwan/models/configuration/feature_profile/sdwan/routing/ospf.py, catalystwan/models/configuration/feature_profile/sdwan/routing/ospfv3.py, catalystwan/models/configuration/feature_profile/sdwan/service/eigrp.py, catalystwan/models/configuration/feature_profile/sdwan/service/lan/vpn.py, pyproject.toml
Add correct fields for route policy
=> dev: Fix/route policy fields

ENDPOINTS.md, catalystwan/apigw_auth.py, catalystwan/response.py, catalystwan/session.py, catalystwan/tests/test_vmanage_auth.py, catalystwan/vmanage_auth.py, pyproject.toml
=> dev: sync 0.35.4

catalystwan/models/configuration/feature_profile/sdwan/service/eigrp.py, pyproject.toml
=> dev: Fix tablemap - add refiditem

ENDPOINTS.md, catalystwan/models/configuration/feature_profile/sdwan/acl/ipv4acl.py, catalystwan/models/configuration/feature_profile/sdwan/acl/ipv6acl.py, catalystwan/models/configuration/feature_profile/sdwan/application_priority/traffic_policy.py, catalystwan/models/configuration/feature_profile/sdwan/service/lan/vpn.py, catalystwan/models/configuration/feature_profile/sdwan/system/bfd.py, pyproject.toml
- fix bfd model
- fix vpn lan model
- fix acl model: actions, base_action fields are mutually exclusive, update builder methods
- fix traffic-policy model (encap value can be list <= 20.12)
=> dev: fix bfd, lan-vpn, acl, traffic-data

ENDPOINTS.md, catalystwan/models/configuration/feature_profile/sdwan/service/route_policy.py, catalystwan/models/policy/definition/route_policy.py, pyproject.toml
- allow additional sequence type for `vedgeroute` policy model
- fix `refId` fields in `route-policy` model
=> dev: fix vedgeroute, route-policy

catalystwan/dataclasses.py, catalystwan/endpoints/cluster_management.py, catalystwan/utils/persona.py, pyproject.toml
Add `add_vmanage`, `edit_vmanage` and `get_connected_devices` endpoints for cluster management.
Add Persona enum.
=> Add `add_vmanage`, `edit_vmanage` and `get_connected_devices` endpoints for cluster management

ENDPOINTS.md, catalystwan/api/versions_utils.py, pyproject.toml
local device ip field needs to be used.
=> fix: device ip arguement for listing partitions

ENDPOINTS.md, catalystwan/models/policy/policy_definition.py, pyproject.toml
=> dev: fix service entry validation

catalystwan/models/configuration/feature_profile/sdwan/service/route_policy.py, catalystwan/models/configuration/feature_profile/sdwan/system/logging_parcel.py, pyproject.toml
- route-policy community action entry
- logging parcel priority enum
=> dev: fix parcel models

ENDPOINTS.md, catalystwan/api/mtt_aaa_api.py, pyproject.toml
=> dev: sync with 0.36.1
